### PR TITLE
feat(api): 🚀 Added Flask API for gTTS speech synthesis to text

### PR DESCRIPTION
**Pull request by Ryrahul**
Make sure you run both the next.js and flask(python app/app.py) 
If you want you can add the static folder to git ignore so that the audio is not pushed to guthub or you can leave it as well

### CODE REVIEW

**Comment by r0ld3x** [comment]
> Make sure you run both the next.js and flask(python app/app.py) 
> If you want you can add the static folder to git ignore so that the audio is not pushed to guthub or you can leave it as well

Yhh also we need a way to run flask and next simultaneously.

**Comment by Ryrahul** [comment]
You can run both on separate terminal or you can send the frontend page from the backend itself (for simplicity)

**Comment by r0ld3x** [comment]
> can you add the label hactober-fest accepted if possible? @r0ld3x

added :)

**Comment by Ryrahul** [comment]
thanks

**Pull request merged**
